### ISSUE TITLE
Update __str__ for Analytics model

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website-API#159]
Update the `__str__` method of the `Analytics` model to include the `title` of the `AnalyticsCategory` as well. This is because when adding analytics data such as "Facebook followers" it is difficult to determine which of the options are for "Facebook followers" vs "Twitter followers", "Instagram followers", etc...

<img width="800" alt="Screen Shot 2021-08-29 at 4 15 43 PM" src="https://user-images.githubusercontent.com/8547538/131264197-20c49a9a-cfa6-47b2-8e9c-b1ecf262ad54.png">

**Comment by ThaDeveloper** [comment]
@buckyroberts This has been updated, but we probably need to restructure AnalyticsCategory and Analytics to prevent reverse filter to get the category title unless it affects our current use case.  Instead of having Analytics as many to many field on AnalyticsCategory, we can have AnalyticsCategory as a FK on Analytics model.
![image](https://user-images.githubusercontent.com/12385482/131667504-25a48ce1-dc63-42af-b336-18e932f5bdf1.png)
